spring.application.name=atm
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bisa_atm
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del Backend
server.port=8083

JWT_SECRET=35db76456f541f46b030c030f346c68c96c5280439798e34cab8c11e8a47fecd0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=logysyncempresa@gmail.com
spring.mail.password=nmkawvlajtpozmkb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true